FROM apstech/treina:latest

COPY ./app /var/www/app/

WORKDIR /var/www/app/

RUN rm /etc/apache2/sites-enabled/000-default.conf /etc/apache2/sites-available/000-default.conf 

COPY ./app.conf /etc/apache2/sites-enabled/app.conf

EXPOSE 80 443

# By default, simply start apache.
CMD ["/sbin/entrypoint.sh"]